In [1]:
import numpy as np

In [26]:
class Perceptron:
    def __init__(self,training:np.array,labels:np.array):
        self.x=training
        self.y=labels
        temp=self.augment()
        self.zeroOneNormal=self.negateZero(temp)
        self.w=np.zeros(len(self.zeroOneNormal[0]))
        self.w=self.w.astype(int)

    def augment(self):
        """
        augmentation of test data to absorb theta parameter as a weight
        """
        return np.insert(self.x,0,-1,axis=1)
    
    def negateZero(self,augment):
        """
        negative zero class cases
        """
        zeroClass=np.where(self.y==0)
        augment[zeroClass]=-augment[zeroClass]
        return augment
    
    def train(self):
        """
        training the perceptron by updating self.w
        """
        run=1
        counter=0
        while run:
            print("starting while loop")
            counter=counter+1
            for xi in self.zeroOneNormal:
                print("for loop in ",xi)
                temp=self.w @ xi
                print(temp)
                if temp<=0:
                    self.w=self.w+xi
                    run=1
                    break
                if np.array_equal(xi,self.zeroOneNormal[-1]):
                    run=0
                    print(counter)
                    return
                
    def test(self,inputs:np.array):
        """
        testing with random data
        """
        inputs=np.insert(inputs,0,-1,axis=1)

        decider=self.w@inputs.T
        out=np.zeros(len(inputs))
        print("decider",decider)
        for i in range(len(out)):
            if decider[i]>0:
                out[i]=1
        return out
                

In [27]:
#testing cell
#taking example of AND
trainData=np.array([[0,0],[0,1],[1,0],[1,1]])
labels=np.array([0,0,0,1])
p1=Perceptron(trainData,labels)


print("Augmented:")
print(p1.augment())
print()
print("Zero class negated")
print(p1.zeroOneNormal)
print()
print("training now")
p1.train()
print()
print("weights post training")
print(p1.w)



# for xi in p1.zeroOneNormal:
#     # temp=.w @ xi
#     # print("multiplication")
#     print(xi @ (np.array([2,1,1])))
#     # run=0

Augmented:
[[-1  0  0]
 [-1  0  1]
 [-1  1  0]
 [-1  1  1]]

Zero class negated
[[ 1  0  0]
 [ 1  0 -1]
 [ 1 -1  0]
 [-1  1  1]]

training now
starting while loop
for loop in  [1 0 0]
0
starting while loop
for loop in  [1 0 0]
1
for loop in  [ 1  0 -1]
1
for loop in  [ 1 -1  0]
1
for loop in  [-1  1  1]
-1
starting while loop
for loop in  [1 0 0]
0
starting while loop
for loop in  [1 0 0]
1
for loop in  [ 1  0 -1]
0
starting while loop
for loop in  [1 0 0]
2
for loop in  [ 1  0 -1]
2
for loop in  [ 1 -1  0]
1
for loop in  [-1  1  1]
-1
starting while loop
for loop in  [1 0 0]
1
for loop in  [ 1  0 -1]
0
starting while loop
for loop in  [1 0 0]
2
for loop in  [ 1  0 -1]
2
for loop in  [ 1 -1  0]
0
starting while loop
for loop in  [1 0 0]
3
for loop in  [ 1  0 -1]
3
for loop in  [ 1 -1  0]
2
for loop in  [-1  1  1]
-2
starting while loop
for loop in  [1 0 0]
2
for loop in  [ 1  0 -1]
1
for loop in  [ 1 -1  0]
0
starting while loop
for loop in  [1 0 0]
3
for loop in  [ 1  0 -1]
2
for loop

In [28]:
print(p1.w@p1.augment().T)


print(p1.test(trainData))

[-4 -2 -1  1]
decider [-4 -2 -1  1]
[0. 0. 0. 1.]
